---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vm-agent-config
  namespace: monitoring
data:
  vmagent.yaml: |
    global:
      scrape_interval: 10s
    external_labels:
      datacenter: my_dev
      instance: vmagent
    scrape_configs:
      - job_name: vmagent
        static_configs:
          - targets: ["localhost:8429"]
      - job_name: "kube-state-metrics"
        static_configs:
          - targets: ['kube-state-metrics.monitoring.svc:8080']
