---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmalert-config
  namespace: monitoring
data:
  vmalert.yaml: |
    groups:
      - name: example
        rules:
          - alert: HighMemoryUsage
            expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.1
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Instance {{ $labels.instance }} memory usage is high"
              description: "Instance {{ $labels.instance }} memory usage is above 90% ({{ $value }})."

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app: vmalert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmalert
  template:
    metadata:
      labels:
        app: vmalert
    spec:
      containers:
      - name: vmalert
        image: victoriametrics/vmalert:v1.66.1
        args:
        - -rule=/config/vmalert.yaml
        - -datasource.url=http://vm-single.monitoring:8428
        - -notifier.url=http://alertmanager.monitoring:9093
        resources:
            requests:
              memory: "256Mi"
              cpu: "0.5"
              ephemeral-storage: "3Gi"
            limits:
              memory: "512Mi"
              cpu: "1"
              ephemeral-storage: "5Gi"
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: vmalert-config

---
apiVersion: v1
kind: Service
metadata:
  name: vmalert
  namespace: monitoring
  labels:
    app: vmalert
spec:
  ports:
  - port: 8880
    targetPort: 8880
    protocol: TCP
    name: http
  selector:
    app: vmalert
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vm-alert
  namespace: monitoring
  labels:
    app: vm-alert
    section: monitoring
  annotations:
    cert-manager.io/cluster-issuer: dev-ca-issuer
    cert-manager.io/common-name: vmalert.dpetrenko.ru
    cert-manager.io/subject-organizations: "home dev lab"
    cert-manager.io/subject-countries: "RU"
    cert-manager.io/subject-localities: "Voronezh"
    cert-manager.io/duration: "9125h"
    cert-manager.io/renew-before: "360h"
    cert-manager.io/usages: "server auth"
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-encoding: "PKCS8"
    cert-manager.io/private-key-size: "4096"
    cert-manager.io/private-key-rotation-policy: Always
    nginx.ingress.kubernetes.io/proxy-body-size: 1g
spec:
  ingressClassName: "system-ingress"
  rules:
    - host: vmalert.dpetrenko.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmalert
                port:
                  number: 8880
  tls:
    - hosts:
      - vmalert.dpetrenko.ru
      secretName: vm-alert-tls